### ISSUE TITLE
Wrong Gist URL, No button on GitHub

### ISSUE THREAD

**Issue by shge** [eight04/raw-githack-button#1]
* Gist URL is wrong, it should be:
```js
url = url.replace("gist.github.com/", "gist.githack.com/");
```

* Doesn't show button on GitHub, class name is changed.
<img width="321" alt="SS 2019-04-03 at 12 21 23" src="https://user-images.githubusercontent.com/25113178/55450729-18126b00-560b-11e9-8376-4305dce9d27c.png">

**Comment by eight04** [comment]
Fixed in v0.1.1.
